### ISSUE TITLE
AWM's firing is delayed, and during that time it prevents the user from opening its attachment menu.

### ISSUE THREAD

**Issue by shodanwashere** [HaloOfBlocks/AdditionalGuns#71] opened 2022-07-25 16:54 UTC

**Comment by Autovw** [comment] 2022-07-25 17:03
Unable to replicate as described in the title, can you please provide more information?
Something like a short video or possible even logs would help.

**Comment by DalibeEspesa** [comment] 2022-07-25 17:47
Hi

I am having this issue too, I've attached videos of the issue happening and an image of the modpack. I created a new one to isolate the issue. The issue seems to occur on multiple forge versions. (1.18.2 40.1.68 and 1.18.2 40.1.55)

From my observations, it seems to occur with long range weapons in the Addigional Guns mod in 0.7.0 and 0.7.1.  0.6.1 Does not have this issue.

The rifle and sniper from McCrayfish's mod does not have this issue, with and without the Additional mod installed.

Looking at the logs after the session, no message of interest seems to appear.

https://user-images.githubusercontent.com/109982584/180841223-2d241ef5-0137-4c46-a410-fcfeb456dc8d.mp4

https://user-images.githubusercontent.com/109982584/180841132-4e11960b-9049-4dc7-9ee6-a2900712c694.mp4

![image](https://user-images.githubusercontent.com/109982584/180838675-9189fade-e66f-410d-bae9-9a3b2721908a.png)

**Comment by Igggosha** [comment] 2022-07-25 17:55
It is... lagging. Might actually be a thing you should ask MrCrayFish.

**Comment by Autovw** [comment] 2022-07-25 17:55
Ok, I got it. This is intended behaviour. The fire rate of the AWM has been changed to make it fire *slower* due to it dealing a **lot** of damage per bullet. This is purely for balancing.

**Comment by Autovw** [comment] 2022-07-25 18:08
I'll quickly add something to this for the record: after it was pointed out on Discord it seems to be actually an issue with MrCrayfish's Gun Mod. I believe @Igggosha also wrote something like that, but I didn't read their comment properly and thought the comment would only confuse people, so I deleted it. Sorry about that.

Instead this would need to be reported to [MrCrayfish's Gun Mod](https://github.com/MrCrayfish/MrCrayfishGunMod/issues) because we just utilize features from that mod.

**Comment by CasualNoLifer** [comment] 2022-07-25 18:41
We talked about this in the Discord and you said you would be interested in looking into the issue further. Please put any more information you may have on this in here so we can determine the cause of the issue. Thank you!

**Comment by CasualNoLifer** [comment] 2022-07-26 15:56
The source of this issue has been determined to be the current set projectile life/size/speed on the guns. An attempt at fixing this issue will be made for 0.8.0. The Issue will remain open until it is officially resolved and has been confirmed in 0.8.0 in case more information comes to light. Thank you to everyone who brought this to our attention and to @DalibeEspesa for doing research and testing to help identify the issue.

**Comment by Autovw** [comment] 2022-12-25 09:52
Issue is fixed in Additional Guns 0.8.0.
Thanks for reporting!

**Closed by Autovw** 2022-12-25 09:52 UTC
Labels: bug
