### ISSUE TITLE
Scope does not work all the time

### ISSUE THREAD

**Issue by Kevin257550** [HaloOfBlocks/AdditionalGuns#91] opened 2022-12-12 15:52 UTC
At some weapons the scope does not work, and i ment with this when u look trow it you can not shoot i use 1.19.2 version

can u fix this bc it really will help out 

this a bug

sorry idk how to set the labels projects etc.

**Comment by Autovw** [comment] 2022-12-12 16:22
Thanks for your report.

Would you be able to give us some more information so we can try and replicate your issue?

We would like to know to following things:
- "Some weapons" could mean anything. We would like to know the names of the weapons you are talking about.
- Which scopes did you use? We'd like to know the names of the scopes you tried this with as well.

**Comment by Kevin257550** [comment] 2022-12-12 17:43
well first for all even without the scopes just some of the normal guns when u scope/aim are not working.

So i think thats the problem about it 

bc i tryed to use it also on a other server and it did the same not aim and scope 


List of guns that do not work with scope or aim:

mrfishyguns:
 pistol
shotgun
rifle
gerande launcher
bazooka
heavy rifle

additional guns:
usp
M1014
mammoth
ace of spades
vintorez
Ots-03
banshee
SSG-08
AWM
desert eagle
P250
Magnum

**Comment by Kevin257550** [comment] 2022-12-12 20:35
Weird part is i can fine use it in single player world

**Comment by Kevin257550** [comment] 2022-12-12 20:53
I have reacted in the issues channel

Op ma 12 dec. 2022 om 17:22 schreef Autovw ***@***.***>:

**Comment by CasualNoLifer** [comment] 2022-12-13 01:02
> well first for all even without the scopes just some of the normal guns when u scope/aim are not working.
> 
> So i think thats the problem about it
> 
> bc i tryed to use it also on a other server and it did the same not aim and scope
> 
> I Use the's for a aternos server List of guns that do not work with scope or aim:
> 
> mrfishyguns: pistol shotgun rifle gerande launcher bazooka heavy rifle
> 
> additional guns: usp M1014 mammoth ace of spades vintorez Ots-03 banshee SSG-08 AWM desert eagle P250 Magnum @Autovw

Hi there. Can you please tell me which of the following you're using if any at all?

- TLauncher or any other cracked Minecraft
- Optifine or performance mods
- Fabulous graphics

This issue has historically been caused by the first on the list or some other compatibility issue. 

The other two usually only affect things visually but may be causing you other issues too. 

Another thing to keep in mind is that some of the guns you listed do not have the ability to have a scope on them. The Grenade Launcher, Bazooka, and Magnum for example cannot have a scope on them at all.

Please message me back with any other details so I can help get you closer to solving your issue.

**Comment by Kevin257550** [comment] 2022-12-13 07:43
Well normally when i start it up the mod i get minecraft with a cracked or weird version symbool
i can not show a picture it wount let me

also about this part Another thing to keep in mind is that some of the guns you listed do not have the ability to have a scope on them. The Ace of Spades, Bazooka, and Magnum for example cannot have a scope on them at all.

i know u can't put scope on it but the problems are not the scope it is when u aim with the scope or without the scope some guns can not shoot

**Comment by Kevin257550** [comment] 2022-12-13 08:50
BRUH i found it out i think
BUG some weapons when aiming when holding something in offhand does not work

**Comment by Autovw** [comment] 2022-12-13 17:47
We have looked into the issue report and have been unable to replicate it in both a singleplayer world and a Forge multiplayer server.
This leads us to believe the issue is not caused by Additional Guns, or even MrCrayfish's Gun Mod.

What you could do is look into the following options:
- Make sure you are running a Forge server, and not some other server software that allows you to run plugins and mods.
- This one is more difficult to figure out: but, it is possible you have a mod conflict between MrCrayfish's Gun Mod and another mod. Might be worth to look into.

That said, unless new information can be provided, there's not much we can do about this issue. For this reason I will be closing the issue.

**Closed by Autovw** 2022-12-13 17:47 UTC
Labels: not a bug
